dappforce/subsocial-parachain

.github/workflows/docker-build.yml

trigger the workflow with CI label

add label on PR

---

.dockerignore
Cargo.lock
runtime/src/lib.rs

Prepare runtime to release v0.9.16 upgrade

---

Cargo.lock
node/src/chain_spec.rs
runtime/Cargo.toml
runtime/src/lib.rs

This is runtime upgrade only.
Changed to `spec_version: 5`

Add Vesting and Utility pallets to the parachain

---

.github/workflows/extrinsic-ordering-check-from-compiled.yml
scripts/github/extrinsic-ordering-filter.sh

We need this CI in order to compare between new and old parachain metadata when doing upgrades.

Add CI to compare parachain metadata

---

runtime/src/lib.rs

Allow domains registration

---

.github/workflows/test-code.yml
Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/domains/Cargo.toml
pallets/parachain-utils/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/weights/block_weights.rs
runtime/src/weights/extrinsic_weights.rs
runtime/src/weights/mod.rs
runtime/src/weights/paritydb_weights.rs
runtime/src/weights/rocksdb_weights.rs
runtime/src/xcm_config.rs

I did upgrade from `v0.9.16` to `v0.9.17` in a commit, then did from `v0.9.17` to `v0.9.18` in another commit.

Upgrade to polkadot-v0.9.18.

---

.github/workflows/test-code.yml
Cargo.lock
Cargo.toml
node/Cargo.toml
node/res/subsocial.json
node/src/chain_spec.rs
node/src/cli.rs
node/src/command.rs
node/src/service.rs
pallets/domains/Cargo.toml
pallets/parachain-utils/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/weights/block_weights.rs
runtime/src/weights/extrinsic_weights.rs
runtime/src/weights/mod.rs
runtime/src/weights/paritydb_weights.rs
runtime/src/weights/rocksdb_weights.rs
runtime/src/xcm_config.rs

Upgrade to polkadot-v0.9.18 and redenominate token

---

runtime/src/lib.rs

Fix domains-related deposits

---

scripts/run-benchmark-on.sh

Due to last CLI update it was broken.
Co-Authored-By: Tarek Mohamed Abdalla <tarekkma@gmail.com>

Fix run-benchmarks-on script

---

pallets/permissions/src/lib.rs

Co-Authored-By: Shady Khalifa <shekohex@gmail.com>
Based on: #55

Upgrade `pallet-permission` to the new proc macro

---

pallets/spaces/Cargo.toml
pallets/spaces/rpc/Cargo.toml
pallets/spaces/rpc/runtime-api/Cargo.toml
pallets/spaces/rpc/runtime-api/src/lib.rs
pallets/spaces/rpc/src/lib.rs
pallets/spaces/src/lib.rs
pallets/spaces/src/migrations.rs
pallets/spaces/src/rpc.rs
pallets/spaces/types.json

Copy spaces pallet to parachain

---

pallets/spaces/src/lib.rs
pallets/spaces/src/migrations.rs
pallets/spaces/src/rpc.rs

Upgrade `pallet-spaces` to the new proc macro

---

pallets/posts/Cargo.toml
pallets/posts/rpc/Cargo.toml
pallets/posts/rpc/runtime-api/Cargo.toml
pallets/posts/rpc/runtime-api/src/lib.rs
pallets/posts/rpc/src/lib.rs
pallets/posts/src/functions.rs
pallets/posts/src/lib.rs
pallets/posts/src/rpc.rs
pallets/posts/types.json

Copy posts pallet to parachain

---

pallets/reactions/Cargo.toml
pallets/reactions/rpc/Cargo.toml
pallets/reactions/rpc/runtime-api/Cargo.toml
pallets/reactions/rpc/runtime-api/src/lib.rs
pallets/reactions/rpc/src/lib.rs
pallets/reactions/src/lib.rs
pallets/reactions/src/rpc.rs
pallets/reactions/types.json

Copy reactions pallet to parachain

---

integration-tests/src/mock.rs

Fix `pallet_profiles` in integration-tests mocks

---

Cargo.lock
integration-tests/src/mock.rs
pallets/profiles/src/lib.rs
pallets/roles/src/lib.rs
pallets/roles/src/mock.rs
pallets/space-follows/Cargo.toml
pallets/space-follows/src/lib.rs
pallets/space-ownership/Cargo.toml
pallets/space-ownership/src/lib.rs
pallets/spaces/src/lib.rs
pallets/support/src/traits.rs
pallets/support/src/traits/common.rs
runtime/src/lib.rs

Refactor profiles to spaces as profiles

---

pallets/account-follows/src/lib.rs
pallets/posts/src/lib.rs
pallets/profiles/src/lib.rs
pallets/reactions/src/lib.rs
pallets/roles/src/lib.rs
pallets/space-follows/src/lib.rs
pallets/space-ownership/src/lib.rs
pallets/spaces/src/lib.rs
runtime/src/lib.rs

Enable social calls, correct fees and social calls' weights

---

runtime/src/lib.rs

Replace ensure_root with EnsureOrigin in domains

---

runtime/src/lib.rs

Also fixes issue with allowing `force_register_domain` for every proxy type.

Add new proxy types: SocialActions and Management

---

Cargo.lock
Cargo.toml
pallets/posts/tests/Cargo.toml
pallets/posts/tests/src/comments_tests.rs
pallets/posts/tests/src/lib.rs
pallets/posts/tests/src/mock.rs
pallets/posts/tests/src/post_tests.rs
pallets/posts/tests/src/shared_posts_tests.rs
pallets/posts/tests/src/tests_utils.rs
pallets/reactions/tests/Cargo.toml
pallets/reactions/tests/src/lib.rs
pallets/reactions/tests/src/mock.rs
pallets/reactions/tests/src/tests.rs
pallets/reactions/tests/src/tests_utils.rs
pallets/space-follows/tests/Cargo.toml
pallets/space-follows/tests/src/lib.rs
pallets/space-follows/tests/src/mock.rs
pallets/space-follows/tests/src/tests.rs
pallets/space-follows/tests/src/tests_utils.rs
pallets/space-ownership/tests/Cargo.toml
pallets/space-ownership/tests/src/lib.rs
pallets/space-ownership/tests/src/mock.rs
pallets/space-ownership/tests/src/tests.rs
pallets/space-ownership/tests/src/tests_utils.rs
pallets/spaces/tests/Cargo.toml
pallets/spaces/tests/src/lib.rs
pallets/spaces/tests/src/mock.rs
pallets/spaces/tests/src/tests.rs
pallets/spaces/tests/src/tests_utils.rs

In a batch with #169 
~~Verify pallet and extrinsic ordering has stayed the same. Bump `transaction_version` if not.
Verify new extrinsics have been correctly whitelisted/blacklisted for `BaseCallFilter`.
There are benchmarks added.
Verify weights have been updated for any modified runtime logic.~~
-----
Co-Authored-By: Tarek Mohamed Abdalla tarekkma@users.noreply.github.com

Move tests to corresponding pallets

---

.github/workflows/test-code.yml

- Include `feature/*` and `staging` branches.
- Do not run if changed files don't include any of `.rs`, `.toml` or `.lock` files.

Refactor CI to check and test code

---

runtime/src/lib.rs

~~Verify pallet and extrinsic ordering has stayed the same. Bump `transaction_version` if not.
Verify new extrinsics have been correctly whitelisted/blacklisted for `BaseCallFilter`.
There are benchmarks for newly created extrinsics.
Verify weights have been updated for any modified runtime logic.
There are tests for newly created logic.~~

Add SocialActionsProxy proxy type

---

runtime/src/lib.rs

- Update spec_version to 19
- Update transaction_version to 3

Update runtime versions

---

runtime/src/lib.rs

~~There are benchmarks for newly created extrinsics.
Verify weights have been updated for any modified runtime logic.
There are tests for newly created logic.~~

Revert adjustment runtime changes

---

node/src/chain_spec.rs
pallets/domains/src/lib.rs
pallets/domains/src/mock.rs
pallets/domains/src/tests.rs
pallets/domains/src/types.rs
runtime/src/lib.rs

This also removes `MaxPromoDomainsPerAccount`

Add prices configs to domains pallet

---

Cargo.lock
node/Cargo.toml
node/src/rpc.rs
pallets/domains/Cargo.toml
pallets/domains/rpc/Cargo.toml
pallets/domains/rpc/runtime-api/Cargo.toml
pallets/domains/rpc/runtime-api/src/lib.rs
pallets/domains/rpc/src/lib.rs
pallets/domains/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

Add custom RPC to domains pallet

---

pallets/domains/rpc/runtime-api/src/lib.rs
pallets/domains/rpc/src/lib.rs
pallets/domains/src/lib.rs
pallets/domains/src/mock.rs
pallets/domains/src/tests.rs
pallets/domains/src/types.rs
runtime/src/lib.rs

Add more tests to domains pallet

---

pallets/creator-staking/src/functions.rs
pallets/creator-staking/src/lib.rs
pallets/creator-staking/src/tests/testing_utils.rs
pallets/creator-staking/src/tests/tests.rs
runtime/src/lib.rs

Improve backer rewards formula
